apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: flaskapp-deployment-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - image: codingcorp-docker.pkg.guoxuekun.tech/apitest/docker/nginx:v2
        name: flaskapp
        ports:
          - containerPort: 5001
      imagePullSecrets:
      - name: coding-docker
