apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: tomcat
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - image: {{ .Values.tomcat_image }}
          name: flaskapp
          ports:
            - containerPort: 5002